name: Generate apps.json

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y jq wget curl
          # Install yq
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Generate apps.json
        run: bash ./generate-apps-json.sh

      - name: Commit apps.json if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github-actions"
          git add apps.json
          git diff --cached --quiet || git commit -m "Update apps.json"
          git push
