name: Generate and Release apps.json

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'apps.json'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo avec token pour push
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      # 2️⃣ Installer dépendances
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y jq wget curl
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      # 3️⃣ Générer apps.json
      - name: Generate apps.json
        run: bash ./generate-apps-json.sh

      # 4️⃣ Commit et push automatique si changé
      - name: Commit apps.json if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github-actions"
          git add apps.json
          git diff --cached --quiet || git commit -m "Update apps.json"
          git push origin HEAD:${{ github.ref }}

      # 5️⃣ Déterminer la prochaine version
      - name: Determine next version
        id: version
        run: |
          latest=$(git tag | sort -V | tail -n 1)
          if [ -z "$latest" ]; then
            latest="v1.0.0"
          fi
          base=${latest%.*}
          patch=${latest##*.}
          next="${base}.$((patch + 1))"
          echo "next_version=$next" >> $GITHUB_OUTPUT
          echo "📦 New version: $next"

      # 6️⃣ Créer et pousser le tag Git
      - name: Create and push Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github-actions"
          git tag ${{ steps.version.outputs.next_version }}
          git push origin ${{ steps.version.outputs.next_version }}

      # 7️⃣ Créer la release GitHub
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.next_version }}
          name: "Auto Release ${{ steps.version.outputs.next_version }}"
          body: "Automatic release of latest apps.json generated by CI."
          files: apps.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
