name: Generate apps.json

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo avec token pour push
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      # 2️⃣ Installer dépendances
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y jq wget curl
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      # 3️⃣ Générer apps.json
      - name: Generate apps.json
        run: bash ./generate-apps-json.sh

      # 4️⃣ Commit et push automatique
      - name: Commit apps.json if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github-actions"
          git add apps.json
          git diff --cached --quiet || git commit -m "Update apps.json"
          git push origin HEAD:${{ github.ref }}
